Adding auth helper function

diff --git a/s3-cli b/s3-cli
--- a/s3-cli
+++ b/s3-cli
@@ -508,6 +508,29 @@ inspect_args() {
   fi
 }
 
+# :command.user_lib
+# src/lib/get_auth.sh
+get_auth () {
+  if [ -f "$CREDENTIALS_FILE" ]; then
+    # Source the credentials file
+    source $CREDENTIALS_FILE
+  else
+    echo
+    printf "Credentials are not Set. Run:\n"
+    printf "'s3-cli auth'\n"
+    echo
+    exit 1
+  fi
+
+# Check if the credentials are valid
+  if ! aws sts get-caller-identity > /dev/null 2>&1; then
+    echo "AWS credentials are invalid or expired. Run:"
+    echo
+    printf "'s3-cli auth'\n"
+    echo
+  fi
+}
+
 # :command.command_functions
 # :command.function
 s3_cli_auth_command() {
@@ -1366,33 +1389,6 @@ s3_cli_sync_dir_parse_requirements() {
 
 }
 
-# :command.user_hooks
-before_hook() {
-  # src/before.sh
-  # echo "==[ Before Hook Called ]=="
-
-  # Check if the credentials file exists
-  if [ -f "$CREDENTIALS_FILE" ]; then
-    # Source the credentials file
-    source $CREDENTIALS_FILE
-  else
-    echo
-    printf "Credentials are not Set. Run:\n"
-    printf "'s3-cli auth'\n"
-    echo
-    exit 1
-  fi
-
-  # Check if the credentials are valid
-  if ! aws sts get-caller-identity > /dev/null 2>&1; then
-    echo "AWS credentials are invalid or expired. Run:"
-    echo
-    printf "'s3-cli auth'\n"
-    echo
-  fi
-
-}
-
 # :command.initialize
 initialize() {
   version="0.1.0"
@@ -1413,7 +1409,6 @@ run() {
   declare -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
-  before_hook
 
   case "$action" in
     "auth") s3_cli_auth_command ;;
